# Generated by Django 2.2.4 on 2020-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScholarshipName', models.CharField(max_length=150)),
                ('University', models.CharField(max_length=100)),
                ('ScholarshipValue', models.CharField(max_length=20)),
                ('Deadline', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=50)),
                ('Level', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=2000)),
                ('Link', models.CharField(max_length=100)),
            ],
        ),
    ]
