# Generated by Django 3.0.6 on 2020-06-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPCD', '0004_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='Program',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='Rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='ScholarshipValue',
            field=models.FloatField(default=-1),
        ),
    ]
