# Generated by Django 3.0.6 on 2020-06-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPCD', '0005_auto_20200609_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='Rank',
            field=models.FloatField(default=-1),
        ),
    ]
