# Generated by Django 3.0.6 on 2020-06-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPCD', '0007_auto_20200609_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='Rank',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='ScholarshipValue',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
